name: S4E_CDSL_Workflow

on:
  push:
    branches: [ "b_github_ci" ]
  pull_request:
    branches: [ "b_github_ci" ]

jobs:
  build:
    strategy:
      matrix:
        repo: ['kebi/seal5', 'kebi-be/etiss_wysiwyng']
    runs-on: ubuntu-latest

    steps:
    - name: Check Modified Files
      run: ./get_list_modified_files
      
    - name: Trigger Seal5 and ETISS Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repositry: ${{ matrix.repo }}
        event-type: s4e_cdl_event

        
