name: S4E_CDSL_Workflow

on:
  push:
    branches: [ "b_github_ci" ]
  pull_request:
    branches: [ "b_github_ci" ]

jobs:
  build:
    #strategy:
     # matrix:
      #  repo: ['kebi/seal5', 'kebi-be/etiss_wysiwyng']
    runs-on: ubuntu-latest

    steps:
    - name: Check Modified Files
      run: |
          pwd
          var=$(git diff --name-only HEAD~1 HEAD) 
          echo $var
    - uses: actions/checkout@v4
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: riscv-core-dsl-files
        path: $GITHUB-WORKSPACE/*.core_desc   
    - name: Trigger Seal5 and ETISS Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repositry: ${{ 'kebi/seal5' }}
        event-type: s4e_cdl_event

        
