name: S4E_CDSL_Workflow

on:
  workflow_run:
    branches: [ "b_github_ci" ]
  push:
    branches: [ "b_github_ci" ]
  pull_request:
    branches: [ "b_github_ci" ]

jobs:
  build:
    #strategy:
     # matrix:
      #  repo: ['kebi/seal5', 'kebi-be/etiss_wysiwyng']
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Check Modified Files      
    - run: |
          ls -al
          pwd
          git fetch origin main:main
          var=$(git diff --name-only --diff-filter=d main~ main) 
          echo "List of changed files: "$var
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: riscv-core-dsl-files
        path: /home/runner/work/riscv-coredsl-extensions/riscv-coredsl-extensions/*.core_desc   
    - name: Trigger Seal5 and ETISS Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: ${{ 'kebi/seal5' }}
        event-type: s4e_cdl_event

        
